# file: .github/dependabot.yml
# version: 1.1.0
# guid: b343f8e6-a6b7-4f8a-80dd-59f36d171a43

# Smart Dependabot configuration for merge-srt-subtitles
# Supports: github-actions, python

version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    day: wednesday
    time: '10:00'
    timezone: America/New_York
  open-pull-requests-limit: 5
  commit-message:
    prefix: ci
    include: scope
  labels:
  - dependencies
  - github-actions
  - ci-cd
  groups:
    ci-dependencies:
      patterns:
      - actions/*
      - github/*
      update-types:
      - minor
      - patch
    external-actions:
      patterns:
      - '*'
      exclude-patterns:
      - actions/*
      - github/*
      update-types:
      - minor
      - patch
- package-ecosystem: pip
  directory: /
  schedule:
    interval: weekly
    day: tuesday
    time: '11:00'
    timezone: America/New_York
  open-pull-requests-limit: 3
  commit-message:
    prefix: python
    include: scope
  labels:
  - dependencies
  - tech:python
  allow:
  - dependency-type: direct
  ignore:
  - dependency-name: '*'
    update-types:
    - version-update:semver-major
